- name: Install Apache and starts the service 
  hosts: all
  become: yes 
  tasks: 
  - name: Install the required package 
    yum: 
      name: "{{ ansible_local.system.local.server }}" 
      state: latest 
 
  - name: Start the service 
    service: 
      name: "{{ ansible_local.system.local.webserver }}" 
      state: "{{ ansible_local.system.local.state }}" 

